### Creating empty cave

In [91]:
max_xs = []
max_ys = []
for line in open("Day14_input.txt"):
    x = [point.split(",")[0] for point in line.strip("\n").split(" -> ")]
    y = [point.split(",")[1] for point in line.strip("\n").split(" -> ")]
    max_x, max_y = int(max(x)), int(max(y))
    max_xs.append(max_x)
    max_ys.append(max_y)

import numpy as np

cave = np.zeros(shape = (max(max_ys)+1, max(max_xs)+1))
cave, cave.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 (166, 538))

### Creating rocks

In [92]:
def get_edge(vertex1, vertex2):
    if vertex1[0] == vertex2[0]:
        start, end = min(vertex1[1], vertex2[1]) + 1, max(vertex1[1], vertex2[1])
        return [(vertex1[0], X) for X in range(start, end)]
    elif vertex1[1] == vertex2[1]:
        start, end = min(vertex1[0], vertex2[0]) + 1, max(vertex1[0], vertex2[0])
        return [(Y, vertex1[1]) for Y in range(start, end)]
    else:
        print("I only get orthogonal edges")

for line in open("Day14_input.txt"):
    vertices = [tuple([int(coord) for coord in point.split(",")]) for point in line.strip("\n").split(" -> ")]
    
    points = vertices
    for vertex1, vertex2 in zip(vertices, vertices[1:]):
        points += get_edge(vertex1, vertex2)

    for point in points:
        cave[point[1], point[0]] = 1

### Dripping sand

In [93]:
sand_source = (500, 0)
cave[sand_source[1], sand_source[0]] = 9

def move_grain(x, y):
    
    if y == cave.shape[0]-1:
        return "Bottom"
        
    elif cave[y+1, x] == 0:
        cave[y+1, x] = 2
        cave[y, x] = 0
        return(x, y+1)
    
    elif cave[y+1, x-1] == 0:
        cave[y+1, x-1] = 2
        cave[y, x] = 0
        return(x-1, y+1)
    
    elif cave[y+1, x+1] == 0:
        cave[y+1, x+1] = 2
        cave[y, x] = 0
        return(x+1, y+1)
    else:
        return "Stop"  
    
def drop_grain():
    grain_position = (sand_source[0], sand_source[1] + 1)
    while True:
        grain_position = move_grain(grain_position[0], grain_position[1])
        
        if grain_position == "Bottom":
            print("Reached bottom")
            return 1
        
        if grain_position == "Stop":
            break
        

In [94]:
i = 0
while True:
    _ = drop_grain()
    if _:
        print(i)
        break
    i +=1

Reached bottom
655


## Test

In [85]:
max_xs = []
max_ys = []
for line in open("Day14_test.txt"):
    x = [point.split(",")[0] for point in line.strip("\n").split(" -> ")]
    y = [point.split(",")[1] for point in line.strip("\n").split(" -> ")]
    max_x, max_y = int(max(x)), int(max(y))
    max_xs.append(max_x)
    max_ys.append(max_y)

import numpy as np

cave = np.zeros(shape = (max(max_ys)+1, max(max_xs)+1))

def get_edge(vertex1, vertex2):
    if vertex1[0] == vertex2[0]:
        start, end = min(vertex1[1], vertex2[1]) + 1, max(vertex1[1], vertex2[1])
        return [(vertex1[0], Y) for Y in range(start, end)]
    elif vertex1[1] == vertex2[1]:
        start, end = min(vertex1[0], vertex2[0]) + 1, max(vertex1[0], vertex2[0])
        return [(X, vertex1[1]) for X in range(start, end)]
    else:
        print("I only get orthogonal edges")

for line in open("Day14_test.txt"):
    vertices = [tuple([int(coord) for coord in point.split(",")]) for point in line.strip("\n").split(" -> ")]
    
    points = vertices
    for vertex1, vertex2 in zip(vertices, vertices[1:]):
        points += get_edge(vertex1, vertex2)
        
    for point in points:
        cave[point[1], point[0]] = 1
cave[:,493:]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [86]:
i = 0
while True:
    _ = drop_grain()
    if _:
        print(i)
        break
    i +=1
cave[:,493:]

Reached bottom
24


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 2., 2., 0., 0.],
       [0., 0., 0., 0., 0., 1., 2., 2., 2., 1., 1.],
       [0., 0., 0., 0., 2., 1., 2., 2., 2., 1., 0.],
       [0., 0., 0., 1., 1., 1., 2., 2., 2., 1., 0.],
       [0., 0., 0., 0., 0., 2., 2., 2., 2., 1., 0.],
       [0., 0., 2., 0., 2., 2., 2., 2., 2., 1., 0.],
       [2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])