--- Day 8: Treetop Tree House ---

The expedition comes across a peculiar patch of tall trees all planted carefully in a grid. The Elves explain that a previous expedition planted these trees as a reforestation effort. Now, they're curious if this would be a good location for a tree house.

First, determine whether there is enough tree cover here to keep a tree house hidden. To do this, you need to count the number of trees that are visible from outside the grid when looking directly along a row or column.

The Elves have already launched a quadcopter to generate a map with the height of each tree (your puzzle input). For example:

    30373
    25512
    65332
    33549
    35390

Each tree is represented as a single digit whose value is its height, where 0 is the shortest and 9 is the tallest.

A tree is visible if all of the other trees between it and an edge of the grid are shorter than it. Only consider trees in the same row or column; that is, only look up, down, left, or right from any given tree.

All of the trees around the edge of the grid are visible - since they are already on the edge, there are no trees to block the view. In this example, that only leaves the interior nine trees to consider:

    The top-left 5 is visible from the left and top. (It isn't visible from the right or bottom since other trees of height 5 are in the way.)
    The top-middle 5 is visible from the top and right.
    The top-right 1 is not visible from any direction; for it to be visible, there would need to only be trees of height 0 between it and an edge.
    The left-middle 5 is visible, but only from the right.
    The center 3 is not visible from any direction; for it to be visible, there would need to be only trees of at most height 2 between it and an edge.
    The right-middle 3 is visible from the right.
    In the bottom row, the middle 5 is visible, but the 3 and 4 are not.

With 16 trees visible on the edge and another 5 visible in the interior, a total of 21 trees are visible in this arrangement.

Consider your map; how many trees are visible from outside the grid?


In [17]:
import numpy as np
forest_list = []

for line in open("Day8_input.txt", "r"):
    forest_list.append(list(line.strip("\n")))

forest_array = np.array(forest_list)
forest_array

array([['3', '3', '3', ..., '3', '0', '3'],
       ['1', '3', '4', ..., '1', '3', '0'],
       ['2', '1', '0', ..., '2', '4', '2'],
       ...,
       ['2', '0', '2', ..., '3', '4', '2'],
       ['0', '4', '1', ..., '4', '4', '3'],
       ['4', '2', '0', ..., '0', '4', '2']], dtype='<U1')

In [18]:
visible = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges:
            is_visible = 0
            if forest_array[i, j] > max(forest_array[:i, j]) \
            or forest_array[i, j] > max(forest_array[i+1:, j]) \
            or forest_array[i, j] > max(forest_array[i, :j]) \
            or forest_array[i, j] > max(forest_array[i, j+1:]):
                is_visible = 1
            visible[i][j] = is_visible
            
for edge in edges:
    visible[edge, :] = 1
    visible[:, edge] = 1
    
visible

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 0., 0., ..., 0., 1., 1.],
       ...,
       [1., 0., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [19]:
np.sum(visible)

1546.0

In [20]:
#test
scenic_score = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges: #edges ignored as they will always yield 0
            tree_height = forest_array[i, j]

            if tree_height <= max(forest_array[i+1:, j]):
                down = np.argwhere(forest_array[i+1:, j] >= tree_height)[0][0] + 1
            else:
                down = len(forest_array[i+1:, j])

            if tree_height <= max(forest_array[:i, j]):
                up = np.argwhere(np.flip(forest_array[:i, j]) >= tree_height)[0][0] + 1
            else:
                up = len(forest_array[:i, j])
            
            if tree_height <= max(forest_array[i, :j]):
                left = np.argwhere(np.flip(forest_array[i, :j]) >= tree_height)[0][0] + 1
            else:
                left = len(forest_array[i, :j])
            
            if tree_height <= max(forest_array[i, j+1:]):
                right = np.argwhere(forest_array[i, j+1:] >= tree_height)[0][0] + 1
            else:
                right = len(forest_array[i, j+1:])
            
            scenic_score[i][j] = up * down * left * right
scenic_score

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   4., 154., ...,   2.,   3.,   0.],
       [  0.,   2.,   1., ...,  12.,  24.,   0.],
       ...,
       [  0.,   1.,  12., ...,   2.,  12.,   0.],
       [  0.,  12.,   3., ...,   8.,   1.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [21]:
np.max(scenic_score)

519064.0

# TESTS BELOW

In [22]:
#test
import numpy as np
forest_list = []

for line in open("Day8_test.txt", "r"):
    forest_list.append(list(line.strip("\n")))

forest_array = np.array(forest_list).astype(int)
forest_array

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [23]:
#test
visible = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges:
            is_visible = 0
            if forest_array[i, j] > max(forest_array[:i, j]) \
            or forest_array[i, j] > max(forest_array[i+1:, j]) \
            or forest_array[i, j] > max(forest_array[i, :j]) \
            or forest_array[i, j] > max(forest_array[i, j+1:]):
                is_visible = 1
            visible[i][j] = is_visible
            
for edge in edges:
    visible[edge, :] = 1
    visible[:, edge] = 1
    
visible

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
#test
np.sum(visible)

21.0

In [25]:
#test
scenic_score = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges: #edges ignored as they will always yield 0
            tree_height = forest_array[i, j]

            if tree_height <= max(forest_array[i+1:, j]):
                down = np.argwhere(forest_array[i+1:, j] >= tree_height)[0][0] + 1
            else:
                down = len(forest_array[i+1:, j])

            if tree_height <= max(forest_array[:i, j]):
                up = np.argwhere(np.flip(forest_array[:i, j]) >= tree_height)[0][0] + 1
            else:
                up = len(forest_array[:i, j])
            
            if tree_height <= max(forest_array[i, :j]):
                left = np.argwhere(np.flip(forest_array[i, :j]) >= tree_height)[0][0] + 1
            else:
                left = len(forest_array[i, :j])
            
            if tree_height <= max(forest_array[i, j+1:]):
                right = np.argwhere(forest_array[i, j+1:] >= tree_height)[0][0] + 1
            else:
                right = len(forest_array[i, j+1:])
            
            scenic_score[i][j] = up * down * left * right
            print(f"{(i, j)} - {[up, down, left, right]}")
scenic_score

(1, 1) - [1, 1, 1, 1]
(1, 2) - [1, 2, 1, 2]
(1, 3) - [1, 1, 1, 1]
(2, 1) - [1, 2, 1, 3]
(2, 2) - [1, 1, 1, 1]
(2, 3) - [2, 1, 1, 1]
(3, 1) - [1, 1, 1, 1]
(3, 2) - [2, 1, 2, 2]
(3, 3) - [3, 1, 1, 1]


array([[0., 0., 0., 0., 0.],
       [0., 1., 4., 1., 0.],
       [0., 6., 1., 2., 0.],
       [0., 1., 8., 3., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.max(scenic_score)

8.0