--- Day 8: Treetop Tree House ---

The expedition comes across a peculiar patch of tall trees all planted carefully in a grid. The Elves explain that a previous expedition planted these trees as a reforestation effort. Now, they're curious if this would be a good location for a tree house.

First, determine whether there is enough tree cover here to keep a tree house hidden. To do this, you need to count the number of trees that are visible from outside the grid when looking directly along a row or column.

The Elves have already launched a quadcopter to generate a map with the height of each tree (your puzzle input). For example:

    30373
    25512
    65332
    33549
    35390

Each tree is represented as a single digit whose value is its height, where 0 is the shortest and 9 is the tallest.

A tree is visible if all of the other trees between it and an edge of the grid are shorter than it. Only consider trees in the same row or column; that is, only look up, down, left, or right from any given tree.

All of the trees around the edge of the grid are visible - since they are already on the edge, there are no trees to block the view. In this example, that only leaves the interior nine trees to consider:

    The top-left 5 is visible from the left and top. (It isn't visible from the right or bottom since other trees of height 5 are in the way.)
    The top-middle 5 is visible from the top and right.
    The top-right 1 is not visible from any direction; for it to be visible, there would need to only be trees of height 0 between it and an edge.
    The left-middle 5 is visible, but only from the right.
    The center 3 is not visible from any direction; for it to be visible, there would need to be only trees of at most height 2 between it and an edge.
    The right-middle 3 is visible from the right.
    In the bottom row, the middle 5 is visible, but the 3 and 4 are not.

With 16 trees visible on the edge and another 5 visible in the interior, a total of 21 trees are visible in this arrangement.

Consider your map; how many trees are visible from outside the grid?


In [6]:
import numpy as np
forest_list = []

for line in open("Day8_input.txt", "r"):
    forest_list.append(list(line.strip("\n")))

forest_array = np.array(forest_list)
forest_array

array([['3', '3', '3', ..., '3', '0', '3'],
       ['1', '3', '4', ..., '1', '3', '0'],
       ['2', '1', '0', ..., '2', '4', '2'],
       ...,
       ['2', '0', '2', ..., '3', '4', '2'],
       ['0', '4', '1', ..., '4', '4', '3'],
       ['4', '2', '0', ..., '0', '4', '2']], dtype='<U1')

In [7]:
visible = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges:
            is_visible = 0
            if forest_array[i, j] > max(forest_array[:i, j]) \
            or forest_array[i, j] > max(forest_array[i+1:, j]) \
            or forest_array[i, j] > max(forest_array[i, :j]) \
            or forest_array[i, j] > max(forest_array[i, j+1:]):
                is_visible = 1
            visible[i][j] = is_visible
            
for edge in edges:
    visible[edge, :] = 1
    visible[:, edge] = 1
    
visible

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 0., 0., ..., 0., 1., 1.],
       ...,
       [1., 0., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [8]:
np.sum(visible)

1546.0

In [9]:
#test
scenic_score = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges: #edges ignored as they will always yield 0
            tree_height = forest_array[i, j]

            if tree_height <= max(forest_array[i+1:, j]):
                down = np.argwhere(forest_array[i+1:, j] >= tree_height)[0][0] + 1
            else:
                down = len(forest_array[i+1:, j])

            if tree_height <= max(forest_array[:i, j]):
                up = np.argwhere(np.flip(forest_array[:i, j]) >= tree_height)[0][0] + 1
            else:
                up = len(forest_array[:i, j])
            
            if tree_height <= max(forest_array[i, :j]):
                left = np.argwhere(np.flip(forest_array[i, :j]) >= tree_height)[0][0] + 1
            else:
                left = len(forest_array[i, :j])
            
            if tree_height <= max(forest_array[i, j+1:]):
                right = np.argwhere(forest_array[i, j+1:] >= tree_height)[0][0] + 1
            else:
                right = len(forest_array[i, j+1:])
            
            scenic_score[i][j] = up * down * left * right
scenic_score

(1, 1) - [1, 4, 1, 1]
(1, 2) - [1, 11, 2, 7]
(1, 3) - [1, 1, 1, 1]
(1, 4) - [1, 1, 2, 5]
(1, 5) - [1, 2, 1, 4]
(1, 6) - [1, 1, 1, 3]
(1, 7) - [1, 1, 1, 1]
(1, 8) - [1, 1, 1, 1]
(1, 9) - [1, 2, 7, 3]
(1, 10) - [1, 1, 1, 1]
(1, 11) - [1, 1, 1, 1]
(1, 12) - [1, 3, 12, 5]
(1, 13) - [1, 2, 1, 2]
(1, 14) - [1, 1, 1, 1]
(1, 15) - [1, 1, 3, 1]
(1, 16) - [1, 5, 4, 1]
(1, 17) - [1, 5, 5, 3]
(1, 18) - [1, 2, 1, 2]
(1, 19) - [1, 1, 1, 1]
(1, 20) - [1, 10, 20, 8]
(1, 21) - [1, 2, 1, 7]
(1, 22) - [1, 1, 1, 3]
(1, 23) - [1, 1, 1, 1]
(1, 24) - [1, 1, 1, 1]
(1, 25) - [1, 4, 4, 3]
(1, 26) - [1, 1, 1, 1]
(1, 27) - [1, 2, 2, 1]
(1, 28) - [1, 3, 8, 2]
(1, 29) - [1, 1, 1, 1]
(1, 30) - [1, 3, 2, 1]
(1, 31) - [1, 6, 1, 3]
(1, 32) - [1, 1, 1, 1]
(1, 33) - [1, 1, 1, 1]
(1, 34) - [1, 4, 3, 19]
(1, 35) - [1, 2, 1, 1]
(1, 36) - [1, 2, 2, 6]
(1, 37) - [1, 1, 1, 1]
(1, 38) - [1, 3, 2, 1]
(1, 39) - [1, 1, 3, 3]
(1, 40) - [1, 2, 1, 1]
(1, 41) - [1, 1, 1, 1]
(1, 42) - [1, 3, 6, 6]
(1, 43) - [1, 1, 1, 3]
(1, 44) - [1, 1

(14, 2) - [2, 1, 1, 7]
(14, 3) - [1, 1, 1, 1]
(14, 4) - [1, 1, 2, 4]
(14, 5) - [1, 1, 1, 1]
(14, 6) - [1, 1, 2, 2]
(14, 7) - [1, 1, 1, 1]
(14, 8) - [2, 1, 6, 1]
(14, 9) - [2, 6, 7, 4]
(14, 10) - [1, 1, 1, 1]
(14, 11) - [1, 1, 2, 1]
(14, 12) - [3, 6, 3, 1]
(14, 13) - [1, 1, 4, 1]
(14, 14) - [14, 1, 13, 2]
(14, 15) - [1, 2, 1, 1]
(14, 16) - [14, 7, 16, 2]
(14, 17) - [5, 4, 1, 1]
(14, 18) - [14, 3, 2, 13]
(14, 19) - [7, 10, 1, 2]
(14, 20) - [1, 1, 1, 1]
(14, 21) - [1, 1, 3, 2]
(14, 22) - [1, 1, 1, 1]
(14, 23) - [14, 2, 5, 5]
(14, 24) - [2, 3, 1, 4]
(14, 25) - [1, 1, 1, 1]
(14, 26) - [1, 3, 2, 1]
(14, 27) - [5, 1, 3, 1]
(14, 28) - [5, 2, 5, 2]
(14, 29) - [1, 1, 1, 1]
(14, 30) - [2, 3, 2, 1]
(14, 31) - [14, 7, 31, 30]
(14, 32) - [1, 1, 1, 1]
(14, 33) - [7, 1, 2, 3]
(14, 34) - [1, 2, 1, 1]
(14, 35) - [1, 1, 2, 1]
(14, 36) - [14, 13, 3, 1]
(14, 37) - [14, 2, 1, 1]
(14, 38) - [7, 5, 1, 9]
(14, 39) - [6, 5, 1, 2]
(14, 40) - [3, 1, 1, 1]
(14, 41) - [2, 2, 2, 5]
(14, 42) - [1, 1, 1, 1]
(14, 43) -

(26, 16) - [2, 1, 1, 3]
(26, 17) - [1, 1, 1, 1]
(26, 18) - [1, 1, 1, 1]
(26, 19) - [26, 3, 19, 7]
(26, 20) - [1, 1, 1, 2]
(26, 21) - [2, 1, 1, 1]
(26, 22) - [4, 1, 3, 4]
(26, 23) - [1, 2, 1, 1]
(26, 24) - [3, 4, 2, 2]
(26, 25) - [3, 1, 1, 1]
(26, 26) - [26, 5, 7, 3]
(26, 27) - [1, 1, 1, 1]
(26, 28) - [2, 2, 2, 1]
(26, 29) - [5, 4, 3, 6]
(26, 30) - [1, 1, 1, 5]
(26, 31) - [2, 2, 1, 1]
(26, 32) - [1, 1, 1, 1]
(26, 33) - [5, 1, 3, 2]
(26, 34) - [1, 1, 1, 1]
(26, 35) - [26, 3, 35, 9]
(26, 36) - [1, 1, 1, 1]
(26, 37) - [1, 3, 2, 1]
(26, 38) - [3, 2, 3, 4]
(26, 39) - [4, 3, 1, 1]
(26, 40) - [1, 2, 1, 2]
(26, 41) - [1, 1, 1, 1]
(26, 42) - [2, 4, 7, 1]
(26, 43) - [2, 1, 8, 1]
(26, 44) - [26, 12, 9, 3]
(26, 45) - [1, 1, 1, 1]
(26, 46) - [1, 1, 2, 1]
(26, 47) - [4, 5, 3, 51]
(26, 48) - [1, 1, 1, 1]
(26, 49) - [1, 1, 2, 1]
(26, 50) - [1, 1, 1, 1]
(26, 51) - [1, 2, 4, 7]
(26, 52) - [1, 1, 1, 1]
(26, 53) - [1, 1, 2, 3]
(26, 54) - [1, 1, 1, 1]
(26, 55) - [1, 1, 1, 1]
(26, 56) - [1, 1, 5, 2]
(26, 57)

(38, 5) - [2, 1, 1, 1]
(38, 6) - [2, 3, 1, 1]
(38, 7) - [5, 2, 7, 1]
(38, 8) - [15, 3, 1, 1]
(38, 9) - [4, 3, 1, 3]
(38, 10) - [1, 1, 1, 1]
(38, 11) - [11, 1, 2, 1]
(38, 12) - [38, 5, 12, 1]
(38, 13) - [38, 3, 1, 3]
(38, 14) - [1, 1, 1, 1]
(38, 15) - [1, 1, 1, 1]
(38, 16) - [10, 1, 3, 4]
(38, 17) - [5, 1, 1, 3]
(38, 18) - [1, 2, 1, 1]
(38, 19) - [1, 2, 2, 1]
(38, 20) - [8, 1, 20, 4]
(38, 21) - [2, 1, 1, 1]
(38, 22) - [2, 11, 2, 2]
(38, 23) - [1, 1, 1, 1]
(38, 24) - [8, 7, 4, 3]
(38, 25) - [1, 1, 1, 2]
(38, 26) - [1, 1, 1, 1]
(38, 27) - [2, 2, 3, 12]
(38, 28) - [1, 2, 1, 1]
(38, 29) - [2, 1, 2, 2]
(38, 30) - [1, 4, 1, 1]
(38, 31) - [1, 1, 4, 7]
(38, 32) - [1, 1, 1, 1]
(38, 33) - [1, 1, 1, 3]
(38, 34) - [1, 1, 1, 1]
(38, 35) - [1, 1, 1, 1]
(38, 36) - [1, 1, 3, 2]
(38, 37) - [1, 2, 1, 1]
(38, 38) - [4, 3, 7, 1]
(38, 39) - [1, 5, 12, 1]
(38, 40) - [6, 10, 1, 4]
(38, 41) - [5, 2, 1, 3]
(38, 42) - [3, 1, 1, 1]
(38, 43) - [1, 1, 1, 1]
(38, 44) - [12, 2, 4, 3]
(38, 45) - [1, 1, 1, 1]
(38, 46) 

(49, 95) - [1, 1, 1, 3]
(49, 96) - [1, 1, 1, 1]
(49, 97) - [1, 1, 1, 1]
(50, 1) - [5, 1, 1, 11]
(50, 2) - [1, 1, 1, 2]
(50, 3) - [1, 1, 1, 1]
(50, 4) - [1, 1, 2, 3]
(50, 5) - [1, 1, 1, 1]
(50, 6) - [2, 1, 2, 1]
(50, 7) - [3, 5, 6, 3]
(50, 8) - [1, 1, 1, 2]
(50, 9) - [1, 1, 1, 1]
(50, 10) - [1, 1, 3, 2]
(50, 11) - [3, 1, 1, 1]
(50, 12) - [3, 1, 11, 1]
(50, 13) - [2, 1, 1, 1]
(50, 14) - [50, 2, 14, 22]
(50, 15) - [1, 1, 1, 1]
(50, 16) - [11, 18, 2, 2]
(50, 17) - [1, 1, 1, 1]
(50, 18) - [14, 2, 2, 8]
(50, 19) - [1, 1, 1, 1]
(50, 20) - [1, 1, 1, 1]
(50, 21) - [1, 1, 3, 1]
(50, 22) - [1, 1, 4, 4]
(50, 23) - [1, 1, 1, 1]
(50, 24) - [1, 1, 1, 1]
(50, 25) - [1, 1, 1, 1]
(50, 26) - [3, 6, 8, 7]
(50, 27) - [2, 1, 1, 1]
(50, 28) - [3, 5, 2, 5]
(50, 29) - [1, 2, 1, 4]
(50, 30) - [1, 1, 1, 1]
(50, 31) - [1, 1, 1, 1]
(50, 32) - [1, 1, 1, 1]
(50, 33) - [8, 6, 7, 3]
(50, 34) - [5, 2, 1, 2]
(50, 35) - [1, 1, 1, 1]
(50, 36) - [9, 2, 22, 14]
(50, 37) - [1, 1, 1, 1]
(50, 38) - [1, 6, 2, 4]
(50, 39) - [1, 

(62, 70) - [2, 1, 2, 1]
(62, 71) - [1, 1, 3, 4]
(62, 72) - [3, 1, 1, 3]
(62, 73) - [1, 1, 1, 2]
(62, 74) - [1, 1, 1, 1]
(62, 75) - [4, 36, 4, 4]
(62, 76) - [11, 2, 1, 3]
(62, 77) - [1, 1, 1, 1]
(62, 78) - [1, 1, 2, 1]
(62, 79) - [14, 6, 4, 19]
(62, 80) - [1, 1, 1, 1]
(62, 81) - [4, 6, 2, 17]
(62, 82) - [1, 2, 1, 1]
(62, 83) - [3, 2, 1, 3]
(62, 84) - [1, 1, 1, 2]
(62, 85) - [1, 1, 1, 1]
(62, 86) - [9, 4, 5, 3]
(62, 87) - [1, 1, 1, 2]
(62, 88) - [1, 2, 1, 1]
(62, 89) - [6, 2, 8, 9]
(62, 90) - [1, 1, 1, 1]
(62, 91) - [1, 1, 1, 1]
(62, 92) - [1, 1, 3, 1]
(62, 93) - [5, 4, 4, 1]
(62, 94) - [1, 2, 1, 4]
(62, 95) - [1, 1, 1, 1]
(62, 96) - [2, 3, 2, 1]
(62, 97) - [3, 2, 1, 1]
(63, 1) - [2, 3, 1, 1]
(63, 2) - [3, 4, 2, 1]
(63, 3) - [2, 35, 3, 2]
(63, 4) - [7, 2, 1, 1]
(63, 5) - [5, 1, 2, 4]
(63, 6) - [1, 1, 1, 1]
(63, 7) - [2, 1, 2, 2]
(63, 8) - [1, 1, 1, 1]
(63, 9) - [8, 35, 9, 9]
(63, 10) - [4, 14, 1, 7]
(63, 11) - [1, 1, 1, 1]
(63, 12) - [1, 1, 2, 1]
(63, 13) - [1, 2, 3, 4]
(63, 14) - [1, 1,

(74, 59) - [2, 1, 1, 1]
(74, 60) - [1, 7, 6, 6]
(74, 61) - [1, 1, 1, 2]
(74, 62) - [1, 2, 1, 1]
(74, 63) - [14, 3, 3, 3]
(74, 64) - [3, 1, 1, 2]
(74, 65) - [1, 1, 1, 1]
(74, 66) - [12, 2, 28, 32]
(74, 67) - [4, 1, 1, 1]
(74, 68) - [2, 2, 1, 1]
(74, 69) - [5, 1, 3, 12]
(74, 70) - [1, 1, 1, 1]
(74, 71) - [2, 1, 2, 2]
(74, 72) - [1, 1, 1, 1]
(74, 73) - [1, 2, 4, 2]
(74, 74) - [2, 1, 1, 1]
(74, 75) - [6, 4, 6, 3]
(74, 76) - [1, 1, 1, 1]
(74, 77) - [2, 4, 2, 1]
(74, 78) - [2, 1, 3, 3]
(74, 79) - [3, 3, 1, 2]
(74, 80) - [1, 3, 1, 1]
(74, 81) - [5, 24, 12, 5]
(74, 82) - [1, 1, 1, 1]
(74, 83) - [7, 1, 1, 3]
(74, 84) - [1, 4, 1, 2]
(74, 85) - [1, 2, 1, 1]
(74, 86) - [2, 24, 5, 12]
(74, 87) - [1, 1, 1, 1]
(74, 88) - [1, 7, 2, 5]
(74, 89) - [1, 1, 1, 1]
(74, 90) - [2, 1, 1, 3]
(74, 91) - [1, 1, 1, 1]
(74, 92) - [4, 4, 2, 1]
(74, 93) - [1, 24, 7, 5]
(74, 94) - [5, 1, 1, 4]
(74, 95) - [1, 1, 1, 1]
(74, 96) - [1, 1, 1, 1]
(74, 97) - [1, 2, 1, 1]
(75, 1) - [3, 1, 1, 2]
(75, 2) - [1, 1, 1, 1]
(75, 3) 

(87, 39) - [1, 1, 1, 1]
(87, 40) - [1, 2, 3, 6]
(87, 41) - [1, 4, 1, 1]
(87, 42) - [1, 4, 1, 4]
(87, 43) - [3, 1, 1, 3]
(87, 44) - [1, 1, 1, 2]
(87, 45) - [1, 1, 1, 1]
(87, 46) - [2, 1, 6, 3]
(87, 47) - [1, 1, 1, 1]
(87, 48) - [1, 1, 2, 1]
(87, 49) - [4, 11, 12, 22]
(87, 50) - [1, 1, 1, 1]
(87, 51) - [1, 1, 1, 1]
(87, 52) - [2, 1, 3, 2]
(87, 53) - [1, 1, 1, 1]
(87, 54) - [1, 11, 5, 7]
(87, 55) - [1, 3, 1, 3]
(87, 56) - [2, 1, 1, 2]
(87, 57) - [1, 1, 1, 1]
(87, 58) - [2, 3, 3, 3]
(87, 59) - [1, 6, 1, 2]
(87, 60) - [2, 1, 1, 1]
(87, 61) - [2, 1, 7, 1]
(87, 62) - [1, 3, 1, 5]
(87, 63) - [1, 7, 1, 4]
(87, 64) - [1, 1, 1, 1]
(87, 65) - [1, 1, 2, 1]
(87, 66) - [3, 1, 1, 1]
(87, 67) - [7, 4, 5, 4]
(87, 68) - [2, 1, 1, 2]
(87, 69) - [1, 2, 1, 1]
(87, 70) - [1, 3, 2, 1]
(87, 71) - [4, 11, 22, 27]
(87, 72) - [2, 1, 1, 2]
(87, 73) - [1, 1, 1, 1]
(87, 74) - [1, 5, 3, 6]
(87, 75) - [3, 2, 1, 1]
(87, 76) - [2, 6, 1, 2]
(87, 77) - [1, 2, 1, 1]
(87, 78) - [1, 3, 2, 2]
(87, 79) - [2, 4, 1, 1]
(87, 80) 

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   4., 154., ...,   2.,   3.,   0.],
       [  0.,   2.,   1., ...,  12.,  24.,   0.],
       ...,
       [  0.,   1.,  12., ...,   2.,  12.,   0.],
       [  0.,  12.,   3., ...,   8.,   1.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [10]:
np.max(scenic_score)

519064.0

# TESTS BELOW

In [11]:
#test
import numpy as np
forest_list = []

for line in open("Day8_test.txt", "r"):
    forest_list.append(list(line.strip("\n")))

forest_array = np.array(forest_list).astype(int)
forest_array

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [12]:
#test
visible = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges:
            is_visible = 0
            if forest_array[i, j] > max(forest_array[:i, j]) \
            or forest_array[i, j] > max(forest_array[i+1:, j]) \
            or forest_array[i, j] > max(forest_array[i, :j]) \
            or forest_array[i, j] > max(forest_array[i, j+1:]):
                is_visible = 1
            visible[i][j] = is_visible
            
for edge in edges:
    visible[edge, :] = 1
    visible[:, edge] = 1
    
visible

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
#test
np.sum(visible)

21.0

In [14]:
#test
scenic_score = np.zeros(forest_array.shape)
edges = [0, forest_array.shape[0]-1]

for i in range(forest_array.shape[0]):
    for j in range(forest_array.shape[1]):
        if i not in edges and j not in edges: #edges ignored as they will always yield 0
            tree_height = forest_array[i, j]

            if tree_height <= max(forest_array[i+1:, j]):
                down = np.argwhere(forest_array[i+1:, j] >= tree_height)[0][0] + 1
            else:
                down = len(forest_array[i+1:, j])

            if tree_height <= max(forest_array[:i, j]):
                up = np.argwhere(np.flip(forest_array[:i, j]) >= tree_height)[0][0] + 1
            else:
                up = len(forest_array[:i, j])
            
            if tree_height <= max(forest_array[i, :j]):
                left = np.argwhere(np.flip(forest_array[i, :j]) >= tree_height)[0][0] + 1
            else:
                left = len(forest_array[i, :j])
            
            if tree_height <= max(forest_array[i, j+1:]):
                right = np.argwhere(forest_array[i, j+1:] >= tree_height)[0][0] + 1
            else:
                right = len(forest_array[i, j+1:])
            
            scenic_score[i][j] = up * down * left * right
            print(f"{(i, j)} - {[up, down, left, right]}")
scenic_score

(1, 1) - [1, 1, 1, 1]
(1, 2) - [1, 2, 1, 2]
(1, 3) - [1, 1, 1, 1]
(2, 1) - [1, 2, 1, 3]
(2, 2) - [1, 1, 1, 1]
(2, 3) - [2, 1, 1, 1]
(3, 1) - [1, 1, 1, 1]
(3, 2) - [2, 1, 2, 2]
(3, 3) - [3, 1, 1, 1]


array([[0., 0., 0., 0., 0.],
       [0., 1., 4., 1., 0.],
       [0., 6., 1., 2., 0.],
       [0., 1., 8., 3., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.max(scenic_score)

8.0